### ISSUE TITLE
 Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by liefh** [kuafuai/DevOpsGPT#108]
Traceback (most recent call last):                                                                                           
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm.py", line 15, in chatCompletion                                           
    message, success = obj.chatCompletion(context)                                                                           
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm_basic.py", line 73, in chatCompletion                                     
    raise e                                                                                                                  
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm_basic.py", line 59, in chatCompletion                                     
    response = openai.ChatCompletion.create(                                                                                 
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create                 
    return super().create(*args, **kwargs)                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create   
    response, _, api_key = requestor.request(                                                                                
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 298, in request                               
    resp, got_stream = self._interpret_response(result, stream)                                                              
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 700, in _interpret_response                   
    self._interpret_response_line(                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 763, in _interpret_response_line              
    raise self.handle_error_response(                                                                                        
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.                    
                                                                                                                             
During handling of the above exception, another exception occurred:                                                          
                                                                                                                             
Traceback (most recent call last):                                                                                           
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm.py", line 19, in chatCompletion                                           
    message, success = obj.chatCompletion(context)                                                                           
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm_basic.py", line 73, in chatCompletion                                     
    raise e                                                                                                                  
  File "/root/DevOpsGPT/backend/app/pkgs/tools/llm_basic.py", line 59, in chatCompletion                                     
    response = openai.ChatCompletion.create(                                                                                 
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create                 
    return super().create(*args, **kwargs)                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create   
    response, _, api_key = requestor.request(                                                                                
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 298, in request                               
    resp, got_stream = self._interpret_response(result, stream)                                                              
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 700, in _interpret_response                   
    self._interpret_response_line(                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 763, in _interpret_response_line              
    raise self.handle_error_response(                                                                                        
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.                    
Traceback (most recent call last):                                                                                           
  File "/root/DevOpsGPT/backend/app/controllers/common.py", line 9, in decorated_function                                    
    result = func(*args, **kwargs)                                                                                           
  File "/root/DevOpsGPT/backend/app/controllers/step_requirement.py", line 23, in clarify                                    
    msg, success = clarifyRequirement(userPrompt, globalContext, appArchitecture)                                            
  File "/root/DevOpsGPT/backend/app/pkgs/prompt/prompt.py", line 19, in clarifyRequirement                                   
    return obj.clarifyRequirement(userPrompt, globalContext, appArchitecture)                                                
  File "/root/DevOpsGPT/backend/app/pkgs/prompt/requirement_basic.py", line 80, in clarifyRequirement                        
    return json.loads(message), success                                                                                      
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads                                                            
    return _default_decoder.decode(s)                                                                                        
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode                                                            
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                        
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode                                                        
    raise JSONDecodeError("Expecting value", s, err.value) from None                                                         
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                      
172.30.192.1 - - [14/Sep/2023 18:35:53] "POST /step_requirement/clarify HTTP/1.1" 200 -

**Comment by booboosui** [comment]
"You exceeded your current quota"

Log in to openai and check whether the bills and tokens are expired
