### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by fadi9696** [kuafuai/DevOpsGPT#29]
I just love your work and wanted to test this amazing project, but i got this error every time i do the prompt ..

see photo below

![image](https://github.com/kuafuai/DevOpsGPT/assets/73393700/5a5c76d9-78a3-4183-9f84-14b8b5ad1cb5)

**Comment by booboosui** [comment]
Please provide the log of running terminal

**Comment by fadi9696** [comment]
Sure here you go :

Traceback (most recent call last):
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\tools\llm.py", line 15, in chatCompletion
    message, success = obj.chatCompletion(context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\tools\llm_basic.py", line 40, in chatCompletion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\tools\llm.py", line 19, in chatCompletion
    message, success = obj.chatCompletion(context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\tools\llm_basic.py", line 40, in chatCompletion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
Traceback (most recent call last):
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\controllers\common.py", line 9, in decorated_function
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\controllers\step_requirement.py", line 21, in clarify
    msg, success = clarifyRequirement(userPrompt, globalContext)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\prompt\prompt.py", line 19, in clarifyRequirement
    return obj.clarifyRequirement(user_prompt, global_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Aitests\DevOpsGPT\DevOpsGPT-0.6.20\backend\app\pkgs\prompt\requirement_basic.py", line 85, in clarifyRequirement
    return json.loads(message), success
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FadiN\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
127.0.0.1 - - [05/Aug/2023 15:19:08] "POST /step_requirement/clarify HTTP/1.1" 200 -

**Comment by booboosui** [comment]
"openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details."

According to this log, your openai should be out of use limit, you can go to the openai official website to confirm

**Comment by fadi9696** [comment]
Its working ! Thanks

**Comment by fadi9696** [comment]
Do you have some prompt examples that you can provide to us  ? i would like to make a video for arab community about your tool

**Comment by booboosui** [comment]
Thank you very much, we have some demo cases that you can try:

1. Select the Java application template：Develop an interface for adding users. The user information includes id, username, sex, and age

2. Choose a common application template: Develop a web game, there is a small ball at the bottom of the screen, and control the small ball through the left and right keys of the keyboard to avoid obstacles flying from the top of the screen, obstacles appear every second

**Comment by fadi9696** [comment]
You are awesome !!!
