### ISSUE TITLE
启动项目，出现报错信息 ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' 

### ISSUE THREAD

**Issue by xuxiluan** [kuafuai/DevOpsGPT#43]
启动命令python3.11 backend/run.py
启动项目，出现报错信息如下：

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.101.173:8081
Press CTRL+C to quit
Traceback (most recent call last):
  File "/Users/xxl/Documents/app/DevOpsGPT/backend/run.py", line 51, in <module>
    app.run(host=BACKEND_HOST, port=BACKEND_PORT, debug=BACKEND_DEBUG)
  File "/Users/xxl/anaconda3/lib/python3.11/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/xxl/anaconda3/lib/python3.11/site-packages/werkzeug/serving.py", line 1097, in run_simple
    run_with_reloader(
  File "/Users/xxl/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 440, in run_with_reloader
    reloader = reloader_loops[reloader_type](
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxl/anaconda3/lib/python3.11/site-packages/werkzeug/_reloader.py", line 315, in __init__
    from watchdog.events import EVENT_TYPE_OPENED
ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' (/Users/xxl/anaconda3/lib/python3.11/site-packages/watchdog/events.py)

**Comment by booboosui** [comment]
试试这个 方法：https://stackoverflow.com/questions/76228417/cannot-import-name-event-type-opened-from-watchdog-events
