### ISSUE TITLE
Failed to access GPT

### ISSUE THREAD

**Issue by stonedswede** [kuafuai/DevOpsGPT#74]
Get this from both windows and Docker. 

Error: Failed to access GPT, please check whether your network can connect to GPT and terminal proxy is running properly.

Some files failes to write or check.

**Comment by booboosui** [comment]
Can your terminal access the openai web address normally?

To test the network connectivity, run the ```curl -v https://api.openai.com``` command

**Comment by stonedswede** [comment]
VERBOSE: GET with 0-byte payload
curl : { "error": { "message": "Invalid URL (GET /)", "type": "invalid_request_error", "param": null, "code": null } }
At line:1 char:1
+ curl -v https://api.openai.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by stonedswede** [comment]
Traceback (most recent call last):
  File "C:\Users\johan\OneDrive\Skrivbord\DevOpsGPT-fix-win\backend\app\controllers\common.py", line 9, in decorated_function
    result = func(*args, **kwargs)
  File "C:\Users\johan\OneDrive\Skrivbord\DevOpsGPT-fix-win\backend\app\controllers\workspace.py", line 45, in create
    success, msg = pullCode(ws_path, gitPath, base_branch, fature_branch)
  File "C:\Users\johan\OneDrive\Skrivbord\DevOpsGPT-fix-win\backend\app\pkgs\devops\git_tools.py", line 13, in pullCode
    result = subprocess.run(['git', 'clone', '-b', base_branch, gitUrl, repo_path], capture_output=True, text=True, cwd=ws_path)
  File "C:\Users\johan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\johan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\johan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Det går inte att hitta filen

**Comment by av8dtop** [comment]
我猜測 有可能是設定檔編碼問題
我建議作者改成utf-8的模式
開發開源模式大致上都是用utf-8可以讓國際所有人都可以使用
而我有遇到類似問題就把註解全部刪除即可

看是不是這個問題
